### PR TITLE
Data updates

### PR DESCRIPTION
**Pull request by jessibreen**
I've updated the data, the links to the data sources, and fixed the breaks that occurred from column name changes in the data.

### CODE REVIEW

**Comment by chaserx** [comment]
@blakeshall if you could take a look please. we'll need to promote this change and master into the `gh-pages` branch. thanks!!

**Comment by chaserx** [comment]
Thanks @jessibreen !!

**Review by blakeshall — APPROVED** [review]
👍 Awesome!

**Comment by chaserx** [comment]
I pushed master into gh-pages. looks good.

**Pull request merged**
